In [75]:
from ultralytics import YOLO

# Load a pretrained YOLO11n-pose Pose model
model = YOLO("yolo11m-pose.pt")

# Run inference on an image
results = model("trainer.png", conf=0.3, imgsz=160, max_det=1)  # results list


image 1/1 c:\Users\uprao\OneDrive\Desktop\MotionMatch\model\trainer.png: 96x160 1 person, 89.3ms
Speed: 0.0ms preprocess, 89.3ms inference, 1.0ms postprocess per image at shape (1, 3, 96, 160)


In [76]:
for r in results:
    points1 = r.keypoints.xy.numpy()
    print("Calib image")
    print(points1)  # print the Keypoints object containing the detected keypoints

Calib image
[[[     936.15       295.6]
  [     952.64      280.99]
  [     920.91      280.47]
  [     972.91      296.14]
  [     898.56       293.2]
  [     1000.7      399.51]
  [     845.69      386.08]
  [     1072.7      494.82]
  [     755.89      459.27]
  [     1143.8      555.83]
  [     685.25      527.79]
  [     964.99      630.74]
  [     864.06      628.08]
  [     975.16      811.23]
  [     850.28      818.19]
  [     983.67      965.16]
  [     825.68      987.27]]]


In [77]:
results2 = model("user.png", conf=0.3, imgsz=160, max_det=1)  # results list
for r in results2:
    points2 = r.keypoints.xy.numpy()
    print("Test image")
    print(points2)  # print the Keypoints object containing the detected keypoints


image 1/1 c:\Users\uprao\OneDrive\Desktop\MotionMatch\model\user.png: 96x160 1 person, 153.6ms
Speed: 2.1ms preprocess, 153.6ms inference, 2.0ms postprocess per image at shape (1, 3, 96, 160)
Test image
[[[     967.78      259.41]
  [     983.98      245.53]
  [     952.92      244.66]
  [     1002.3       254.1]
  [     932.35      252.08]
  [     1030.7      341.25]
  [      884.1      338.92]
  [     1094.9      442.18]
  [     797.27      428.62]
  [     1184.5      519.01]
  [     710.47      478.71]
  [     988.19      578.29]
  [     897.77      577.84]
  [     983.68      761.88]
  [     896.69      766.31]
  [     982.91      939.92]
  [     898.39      949.14]]]


In [6]:
print(points1[0][5])
print(points2[0][5])

[     1034.7      291.68]
[     240.41      116.15]


In [78]:
points1[0][:, 0] -= points1[0][5, 0]
points1[0][:, 1] -= points1[0][5, 1]
print("Calib image scaled")
print(points1[0])

Calib image scaled
[[    -64.563     -103.91]
 [    -48.066     -118.52]
 [    -79.797     -119.04]
 [      -27.8     -103.37]
 [    -102.15     -106.31]
 [          0           0]
 [    -155.02     -13.426]
 [     71.974      95.308]
 [    -244.82      59.761]
 [     143.11      156.32]
 [    -315.46      128.28]
 [    -35.717      231.24]
 [    -136.64      228.57]
 [    -25.544      411.72]
 [    -150.43      418.68]
 [    -17.035      565.65]
 [    -175.03      587.76]]


In [79]:
points2[0][:, 0] -= points2[0][5, 0]
points2[0][:, 1] -= points2[0][5, 1]
print("Test image scaled")
print(points2[0])

Test image scaled
[[    -62.915     -81.838]
 [    -46.716     -95.717]
 [    -77.783     -96.588]
 [    -28.357     -87.145]
 [    -98.351     -89.172]
 [          0           0]
 [     -146.6      -2.325]
 [     64.167      100.93]
 [    -233.43      87.372]
 [     153.84      177.76]
 [    -320.23      137.46]
 [     -42.51      237.04]
 [    -132.92      236.59]
 [    -47.019      420.63]
 [       -134      425.07]
 [    -47.783      598.68]
 [    -132.31      607.89]]


In [80]:
delta = points1[0] - points2[0]
print(delta)

[[    -1.6471     -22.071]
 [    -1.3505     -22.799]
 [    -2.0145     -22.453]
 [    0.55756      -16.22]
 [    -3.8005     -17.142]
 [          0           0]
 [    -8.4227     -11.101]
 [     7.8069      -5.621]
 [     -11.39     -27.611]
 [    -10.731     -21.443]
 [     4.7763     -9.1859]
 [     6.7936      -5.806]
 [    -3.7186     -8.0183]
 [     21.475     -8.9074]
 [    -16.424     -6.3875]
 [     30.748      -33.03]
 [     -42.72      -20.13]]


In [83]:
import pickle

file = open("scale.pkl", "wb")

# dump information to that file
pickle.dump(delta, file)

In [81]:
points2[0] += delta
print(points2[0])

[[    -64.563     -103.91]
 [    -48.066     -118.52]
 [    -79.797     -119.04]
 [      -27.8     -103.37]
 [    -102.15     -106.31]
 [          0           0]
 [    -155.02     -13.426]
 [     71.974      95.308]
 [    -244.82      59.761]
 [     143.11      156.32]
 [    -315.46      128.28]
 [    -35.717      231.24]
 [    -136.64      228.57]
 [    -25.544      411.72]
 [    -150.43      418.68]
 [    -17.035      565.65]
 [    -175.03      587.76]]


In [82]:
import math

# Total Euclidean distance between all points of 2 arays
diff = 0
for i in range(0, 17):
    # print(math.dist(points1[0][i], points2[0][i]))
    diff += math.dist(points1[0][i], points2[0][i])

print(diff)

0.0
