In [1]:
from ultralytics import YOLO

# Load a pretrained YOLO11n-pose Pose model
model = YOLO("yolo11m-pose.pt")

# Run inference on an image
results = model("tframe1.png", conf=0.3, imgsz=160, max_det=1, save=True)  # results list


image 1/1 c:\Users\uprao\OneDrive\Desktop\MotionMatch\model\tframe1.png: 96x160 1 person, 108.6ms
Speed: 0.5ms preprocess, 108.6ms inference, 2.0ms postprocess per image at shape (1, 3, 96, 160)
Results saved to runs\pose\predict4


In [2]:
for r in results:
    points1 = r.keypoints.xy.numpy()
    print("Calib image")
    print(points1)  # print the Keypoints object containing the detected keypoints

Calib image
[[[     950.82      368.16]
  [     962.82      354.31]
  [     936.17      353.59]
  [     974.55      365.96]
  [     910.03      362.95]
  [     997.05      459.97]
  [     866.19      455.27]
  [     1017.2      570.62]
  [     836.81      563.96]
  [     1022.8      675.67]
  [     836.25      663.35]
  [     967.71      676.95]
  [     881.57      675.57]
  [     957.33      851.62]
  [     880.85       853.3]
  [     945.87      1002.2]
  [     882.83      1005.7]]]


In [4]:
results2 = model("uframe1.png", conf=0.3, imgsz=160, max_det=1, save=True)  # results list
for r in results2:
    points2 = r.keypoints.xy.numpy()
    print("Test image")
    print(points2)  # print the Keypoints object containing the detected keypoints


image 1/1 c:\Users\uprao\OneDrive\Desktop\MotionMatch\model\uframe1.png: 96x160 1 person, 142.1ms
Speed: 2.0ms preprocess, 142.1ms inference, 0.0ms postprocess per image at shape (1, 3, 96, 160)
Results saved to runs\pose\predict4
Test image
[[[     997.15      360.81]
  [     1011.8      346.19]
  [     981.86      345.78]
  [     1026.8      358.12]
  [     958.14      357.21]
  [     1052.9      451.29]
  [     923.83      456.15]
  [     1077.1      562.16]
  [     894.67      576.18]
  [     1090.9      661.85]
  [     872.84       684.1]
  [       1028      664.26]
  [      944.3      666.72]
  [     1032.6       815.5]
  [     957.08      819.03]
  [     1022.5      948.06]
  [      963.1      953.92]]]


In [5]:
points1[0][:, 0] -= points1[0][5, 0]
points1[0][:, 1] -= points1[0][5, 1]
print("Calib image scaled")
print(points1[0])

Calib image scaled
[[     -46.23     -91.811]
 [    -34.227     -105.67]
 [    -60.879     -106.39]
 [    -22.492     -94.009]
 [     -87.02     -97.028]
 [          0           0]
 [    -130.86     -4.7025]
 [     20.166      110.65]
 [    -160.24      103.99]
 [     25.749      215.69]
 [     -160.8      203.38]
 [    -29.332      216.98]
 [    -115.47      215.59]
 [    -39.721      391.64]
 [     -116.2      393.33]
 [    -51.178       542.2]
 [    -114.22      545.69]]


In [6]:
points2[0][:, 0] -= points2[0][5, 0]
points2[0][:, 1] -= points2[0][5, 1]
print("Test image scaled")
print(points2[0])

Test image scaled
[[    -55.706     -90.485]
 [    -41.084      -105.1]
 [    -70.995     -105.52]
 [    -26.033     -93.172]
 [    -94.718     -94.083]
 [          0           0]
 [    -129.03      4.8564]
 [     24.261      110.87]
 [    -158.19      124.88]
 [     37.994      210.55]
 [    -180.02      232.81]
 [    -24.816      212.96]
 [    -108.56      215.43]
 [    -20.227       364.2]
 [    -95.783      367.74]
 [    -30.354      496.76]
 [    -89.755      502.62]]


In [7]:
import pickle

file = open("scale.pkl", "rb")
delta = pickle.load(file)

In [8]:
points2[0] += delta
print(points2[0])

[[    -57.353     -112.56]
 [    -42.435      -127.9]
 [    -73.009     -127.97]
 [    -25.476     -109.39]
 [    -98.519     -111.22]
 [          0           0]
 [    -137.46     -6.2443]
 [     32.068      105.24]
 [    -169.58      97.271]
 [     27.263      189.11]
 [    -175.24      223.62]
 [    -18.022      207.16]
 [    -112.28      207.41]
 [      1.248      355.29]
 [    -112.21      361.35]
 [    0.39423      463.73]
 [    -132.48      482.49]]


In [10]:
import math

diff = 0
for i in range(5, 17):
    # print(math.dist(points1[0][i], points2[0][i]))
    diff += math.dist(points1[0][i], points2[0][i])

print(diff)

353.2814813438586
